{{- if not .Values.scanner.certs.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-certs
data:
  {{- if not .Values.certs.skipCert }}
  tls.crt: {{ .Values.certs.serverCertificate }}  # place server cert
  tls.key: {{ .Values.certs.serverKey }}  # place server key
  {{- end }}
{{- end }}
